random_seed: 1984

feature_names:
#  - intensity # size: 1
#  - return_number # size: 5 (one-hot)
  #  - number_of_returns # size: 5 (one-hot)
  - colors # size: 3
num_features: 3


num_classes: 4      #Si 2 classes, indiquer 1. Sinon, indiquer normalement le nb de classes.

input_mapping:
 0: 0
 1: 1
 2: 2
 3: 3
 4: 2

voxel_size_coarse: 0.8
voxel_size: 0.3

batch_size: 1
test_batch_size: 1
epochs: 200
#loss: FocalTverskyLoss                     #Either FocalTverskyLoss or FocalLoss
loss: FocalTverskyLoss_multiclass                      #Either FocalTverskyLoss or FocalLoss
loss_weights: [[0.7,0.7,0.7,0.7],[0.7,1,1,1]]
#loss_weights: [0.6,0.8]
patience: 30
#weights_name: 'iantsa_anno_reanno72_e300_vxl0002_intrgb_b1_TFL_0505_curbguttfuzed'             #Name of the weight file that will be saved in /model_weights
weights_name: 'test_handcraft_extanded_3c_v9_05050505_0808081_vxl002_unionfind'             #Name of the weight file that will be saved in /model_weights


train_transforms:
  - name: Intensity_RGB_Variation
    params:
      feature_names: ${feature_names}
  - name: Scale
    params:
      feature_names: ${feature_names}
  #  - name: Noise
  #    params:
  #      feature_names: ${feature_names}
  - name: Rotate
    params:
      feature_names: ${feature_names}
  - name: RandomDelete
    params:
      feature_names: ${feature_names}
  - name: RandomCrop
    params:
      feature_names: ${feature_names}
  - name: NormalizeCoordinates
    #  - name: Flip
    #    params:
    #      feature_names: ${feature_names}
  - name: NormalizeFeatures
    params:
      feature_names: ${feature_names}
  - name: RemapClassification
    params:
      class_mapping: ${input_mapping}


test_transforms:
  - name: NormalizeCoordinates
  - name: NormalizeFeatures
    params:
      feature_names: ${feature_names}
  - name: RemapClassification
    params:
      class_mapping: ${input_mapping}